// <auto-generated />
namespace Capstone_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EventLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201807310316443_Event Location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
